import concurrent.futures
import re
import threading
import pandas as pd
import time
from datetime import datetime
from typing import Iterable, List
from vnstock import Vnstock

CURRENT_DATE = datetime.now().strftime("%Y-%m-%d")

# Cấu hình tránh rate limit
SLEEP_TIME = 0.5  # thời gian nghỉ giữa các request để tránh rate limit
MAX_WORKERS = 1 # giới hạn luồng tối đa để không bị chặn


class AdaptiveRateLimiter:
    """Điều chỉnh nhịp gọi API dựa trên phản hồi để tránh rate limit."""

    def __init__(self, initial_sleep: float = SLEEP_TIME, min_sleep: float = 0.25, max_sleep: float = 5.0):
        self.sleep_time = initial_sleep
        self.min_sleep = min_sleep
        self.max_sleep = max_sleep
        self._lock = threading.Lock()

    def current_delay(self) -> float:
        with self._lock:
            return self.sleep_time

    def on_success(self) -> None:
        with self._lock:
            self.sleep_time = max(self.sleep_time * 0.9, self.min_sleep)

    def on_rate_limit(self, wait_seconds: float) -> None:
        with self._lock:
            self.sleep_time = min(max(wait_seconds, self.sleep_time * 1.5), self.max_sleep)

    def on_error(self) -> None:
        with self._lock:
            self.sleep_time = min(self.sleep_time * 1.25, self.max_sleep)

print("Đang sử dụng thư viện: vnstock version 3.x")
print(f"Sẽ lấy tin tức cho ngày: {CURRENT_DATE}")


def _format_news_records(df: pd.DataFrame, symbol: str, target_date) -> List[dict]:
    if df is None or df.empty:
        return []

    if "published_date" in df.columns:
        df["published_date"] = pd.to_datetime(df["published_date"], errors="coerce").dt.date
        df = df[df["published_date"] == target_date]

    if df.empty:
        return []

    news_list = df.to_dict("records")
    formatted = []
    now_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    for news in news_list:
        news["related_ticker"] = symbol
        news["fetched_at"] = now_str

        for key, val in list(news.items()):
            if pd.notna(val) and isinstance(val, (pd.Timestamp, datetime)):
                news[key] = val.strftime("%Y-%m-%d %H:%M:%S")

        formatted.append(
            {
                "id": news.get("id"),
                "author": news.get("author"),
                "friendly_sub_title": news.get("friendly_sub_title"),
                "news_source_link": news.get("news_source_link"),
                "created_at": news.get("created_at"),
                "public_date": news.get("public_date"),
                "updated_at": news.get("updated_at"),
                "lang_code": news.get("lang_code"),
                "news_id": news.get("news_id"),
                "news_short_content": news.get("news_short_content"),
                "news_full_content": news.get("news_full_content"),
                "price_change_pct": news.get("price_change_pct"),
                "related_ticker": news.get("related_ticker"),
                "fetched_at": news.get("fetched_at"),
            }
        )

    return formatted


def _parse_retry_after_seconds(message: str) -> float | None:
    # Thường thấy dạng: "... thử lại sau 41 giây"
    match = re.search(r"thử lại sau\s+(\d+)\s+giây", message, re.IGNORECASE)
    if match:
        return float(match.group(1))
    return None


def _fetch_symbol_news(symbol: str, target_date, sleep_time: float) -> List[dict]:
    try:
        stock = Vnstock().stock(symbol=symbol, source="VCI")
        df = stock.company.news()
        records = _format_news_records(df, symbol, target_date)
        time.sleep(sleep_time)
        return records
    except Exception as e:
        message = str(e)
        retry_wait = _parse_retry_after_seconds(message)
        wait_time = retry_wait if retry_wait is not None else max(sleep_time * 2, 3)
        # Nếu API báo rate limit, ngủ đủ thời gian yêu cầu rồi mới tiếp tục
        print(f"  -> Lỗi khi lấy {symbol}: {message} | ngủ {wait_time:.1f}s")
        time.sleep(wait_time)
        return []


def _deduplicate_news(all_news: Iterable[dict]) -> List[dict]:
    seen_ids = set()
    unique_news = []

    for news in all_news:
        news_id = news.get("id") or news.get("news_title")
        if not news_id or news_id in seen_ids:
            continue

        seen_ids.add(news_id)
        unique_news.append(news)

    return unique_news


def fetch_news_test(target_date: str | None = None, max_workers: int | None = None) -> List[dict]:
    target_date = pd.to_datetime(target_date or datetime.now().date()).date()
    # Ép luôn về 1 luồng để tránh rate limit VCI
    max_workers = MAX_WORKERS
    print(f"\n=== QUÉT TIN TỨC NGÀY {target_date} (1 luồng) ===")

    test_tickers = [
        "YTC",
        "YEG",
        "YBM",
        "YBC",
        "XPH",
        "XMP",
        "XMD",
        "XMC",
        "XLV",
        "XHC",
        "XDH",
        "XDC",
        "X77",
        "X26",
        "X20",
        "WTC",
        "WSS",
        "WSB",
        "WCS",
        "VXT",
        "VXP",
        "VXB",
        "VWS",
        "VW3",
        "VVS",
        "VVN",
        "VUA",
        "VTZ",
        "VTX",
        "VTV",
        "VTS",
        "VTR",
        "VTQ",
        "VTP",
        "VTO",
        "VTM",
        "VTL",
        "VTK",
        "VTJ",
        "VTI",
        "VTH",
        "VTG",
        "VTE",
        "VTD",
        "VTC",
        "VTB",
        "VTA",
        "VST",
        "VSP",
        "VSN",
        "VSM",
        "VSI",
        "VSH",
        "VSG",
        "VSF",
        "VSE",
        "VSC",
        "VSA",
        "VRG",
        "VRE",
        "VRC",
        "VQC",
        "VPX",
        "VPW",
        "VPS",
        "VPR",
        "VPL",
        "VPI",
        "VPH",
        "VPG",
        "VPD",
        "VPC",
        "VPB",
        "VPA",
        "VOS",
        "VOC",
        "VNZ",
        "VNY",
        "VNX",
        "VNT",
        "VNS",
        "VNR",
        "VNP",
        "VNM",
        "VNL",
        "VNI",
        "VNH",
        "VNG",
        "VNF",
        "VNE",
        "VND",
        "VNC",
        "VNB",
        "VNA",
        "VMT",
        "VMS",
        "VMK",
        "VMI",
        "VMG",
        "VMD",
        "VMC",
        "VMA",
        "VLW",
        "VLS",
        "VLP",
        "VLG",
        "VLF",
        "VLC",
        "VLB",
        "VLA",
        "VKP",
        "VKD",
        "VKC",
        "VJC",
        "VIX",
        "VIW",
        "VIT",
        "VIS",
        "VIR",
        "VIP",
        "VIN",
        "VIM",
        "VIH",
        "VIG",
        "VIF",
        "VIE",
        "VID",
        "VIC",
        "VIB",
        "VHM",
        "VHL",
        "VHI",
        "VHH",
        "VHG",
        "VHF",
        "VHE",
        "VHD",
        "VHC",
        "VGV",
        "VGT",
        "VGS",
        "VGR",
        "VGP",
        "VGL",
        "VGI",
        "VGG",
        "VGC",
        "VFS",
        "VFR",
        "VFG",
        "VFC",
        "VET",
        "VES",
        "VEF",
        "VEC",
        "VEA",
        "VE9",
        "VE8",
        "VE4",
        "VE3",
        "VE2",
        "VE1",
        "VDT",
        "VDS",
        "VDP",
        "VDN",
        "VDM",
        "VDL",
        "VDG",
        "VDB",
        "VCX",
        "VCW",
        "VCT",
        "VCS",
        "VCR",
        "VCP",
        "VCM",
        "VCK",
        "VCI",
        "VCG",
        "VCF",
        "VCE",
        "VCC",
        "VCB",
        "VCA",
        "VC9",
        "VC7",
        "VC6",
        "VC5",
        "VC3",
        "VC2",
        "VC1",
        "VBH",
        "VBG",
        "VBC",
        "VBB",
        "VAV",
        "VAT",
        "VAF",
        "VAB",
        "V21",
        "V15",
        "V12",
        "V11",
        "UXC",
        "UTT",
        "USD",
        "USC",
        "UPH",
        "UPC",
        "UNI",
        "UMC",
        "UIC",
        "UEM",
        "UDL",
        "UDJ",
        "UDC",
        "UCT",
        "TYA",
        "TXM",
        "TW3",
        "TVW",
        "TVT",
        "TVS",
        "TVP",
        "TVN",
        "TVM",
        "TVH",
        "TVG",
        "TVD",
        "TVC",
        "TVB",
        "TVA",
        "TV6",
        "TV4",
        "TV3",
        "TV2",
        "TV1",
        "TUG",
        "TTZ",
        "TTT",
        "TTS",
        "TTP",
        "TTN",
        "TTL",
        "TTH",
        "TTG",
        "TTF",
        "TTE",
        "TTD",
        "TTC",
        "TTB",
        "TTA",
        "TT6",
        "TST",
        "TSJ",
        "TSG",
        "TSD",
        "TSC",
        "TSB",
        "TSA",
        "TS5",
        "TS4",
        "TS3",
        "TRV",
        "TRT",
        "TRS",
        "TRC",
        "TRA",
        "TR1",
        "TQW",
        "TQN",
        "TPS",
        "TPP",
        "TPH",
        "TPC",
        "TPB",
        "TOW",
        "TOT",
        "TOS",
        "TOP",
        "TNW",
        "TNV",
        "TNT",
        "TNS",
        "TNP",
        "TNM",
        "TNI",
        "TNH",
        "TNG",
        "TNC",
        "TNB",
        "TNA",
        "TN1",
        "TMX",
        "TMW",
        "TMT",
        "TMS",
        "TMP",
        "TMG",
        "TMC",
        "TMB",
        "TLT",
        "TLP",
        "TLI",
        "TLH",
        "TLG",
        "TLD",
        "TL4",
        "TKU",
        "TKG",
        "TKC",
        "TKA",
        "TJC",
        "TIX",
        "TIS",
        "TIP",
        "TIN",
        "TIG",
        "TIE",
        "TID",
        "THW",
        "THU",
        "THT",
        "THS",
        "THP",
        "THN",
        "THM",
        "THI",
        "THG",
        "THD",
        "THB",
        "TH1",
        "TGP",
        "TGG",
        "TFC",
        "TET",
        "TEL",
        "TEG",
        "TED",
        "TEC",
        "TDW",
        "TDT",
        "TDS",
        "TDP",
        "TDN",
        "TDM",
        "TDI",
        "TDH",
        "TDG",
        "TDF",
        "TDC",
        "TDB",
        "TD6",
        "TCX",
        "TCW",
        "TCT",
        "TCR",
        "TCO",
        "TCM",
        "TCL",
        "TCK",
        "TCJ",
        "TCI",
        "TCH",
        "TCD",
        "TCB",
        "TC6",
        "TBX",
        "TBW",
        "TBT",
        "TBR",
        "TBH",
        "TBD",
        "TBC",
        "TB8",
        "TAW",
        "TAR",
        "TAP",
        "TAN",
        "TAL",
        "TAG",
        "TAC",
        "TAB",
        "TA9",
        "TA6",
        "TA3",
        "T12",
        "SZL",
        "SZG",
        "SZE",
        "SZC",
        "SZB",
        "SWC",
        "SVT",
        "SVN",
        "SVL",
        "SVI",
        "SVH",
        "SVG",
        "SVD",
        "SVC",
        "STW",
        "STT",
        "STS",
        "STP",
        "STL",
        "STK",
        "STH",
        "STG",
        "STC",
        "STB",
        "ST8",
        "SSU",
        "SSN",
        "SSM",
        "SSI",
        "SSH",
        "SSG",
        "SSF",
        "SSC",
        "SSB",
        "SRT",
        "SRF",
        "SRC",
        "SRB",
        "SRA",
        "SQC",
        "SPV",
        "SPP",
        "SPM",
        "SPI",
        "SPH",
        "SPD",
        "SPC",
        "SPB",
        "SPA",
        "SP2",
        "SON",
        "SNZ",
        "SNC",
        "SMT",
        "SMN",
        "SMC",
        "SMB",
        "SMA",
        "SLS",
        "SLD",
        "SKV",
        "SKN",
        "SKH",
        "SKG",
        "SJS",
        "SJM",
        "SJG",
        "SJF",
        "SJE",
        "SJD",
        "SJC",
        "SJ1",
        "SIV",
        "SIP",
        "SII",
        "SIG",
        "SID",
        "SIC",
        "SHX",
        "SHS",
        "SHP",
        "SHN",
        "SHI",
        "SHG",
        "SHE",
        "SHC",
        "SHB",
        "SHA",
        "SGT",
        "SGS",
        "SGR",
        "SGP",
        "SGO",
        "SGN",
        "SGI",
        "SGH",
        "SGD",
        "SGC",
        "SGB",
        "SFN",
        "SFI",
        "SFG",
        "SFC",
        "SEP",
        "SED",
        "SEB",
        "SEA",
        "SDY",
        "SDX",
        "SDV",
        "SDU",
        "SDT",
        "SDP",
        "SDN",
        "SDK",
        "SDJ",
        "SDH",
        "SDG",
        "SDD",
        "SDC",
        "SDB",
        "SDA",
        "SD9",
        "SD8",
        "SD7",
        "SD6",
        "SD5",
        "SD4",
        "SD3",
        "SD2",
        "SD1",
        "SCY",
        "SCV",
        "SCS",
        "SCR",
        "SCO",
        "SCL",
        "SCJ",
        "SCI",
        "SCG",
        "SCD",
        "SCC",
        "SCA",
        "SC5",
        "SBV",
        "SBT",
        "SBS",
        "SBR",
        "SBM",
        "SBL",
        "SBH",
        "SBG",
        "SBD",
        "SBB",
        "SBA",
        "SB1",
        "SAV",
        "SAS",
        "SAP",
        "SAM",
        "SAL",
        "SAF",
        "SAC",
        "SAB",
        "S99",
        "S96",
        "S74",
        "S72",
        "S55",
        "S4A",
        "S27",
        "S12",
        "RYG",
        "RTB",
        "ROS",
        "RIC",
        "RGG",
        "RGC",
        "REE",
        "RDP",
        "RCL",
        "RCD",
        "RCC",
        "RBC",
        "RAT",
        "RAL",
        "QTP",
        "QTC",
        "QST",
        "QSP",
        "QPH",
        "QNW",
        "QNU",
        "QNT",
        "QNS",
        "QNP",
        "QNC",
        "QLT",
        "QLD",
        "QHW",
        "QHD",
        "QCG",
        "QCC",
        "QBS",
        "PYU",
        "PXT",
        "PXS",
        "PXM",
        "PXL",
        "PXI",
        "PXC",
        "PXA",
        "PX1",
        "PWS",
        "PWA",
        "PVY",
        "PVX",
        "PVV",
        "PVT",
        "PVS",
        "PVR",
        "PVP",
        "PVO",
        "PVM",
        "PVL",
        "PVI",
        "PVH",
        "PVG",
        "PVE",
        "PVD",
        "PVC",
        "PVB",
        "PVA",
        "PV2",
        "PTX",
        "PTV",
        "PTT",
        "PTS",
        "PTP",
        "PTO",
        "PTN",
        "PTM",
        "PTL",
        "PTI",
        "PTH",
        "PTG",
        "PTE",
        "PTD",
        "PTC",
        "PTB",
        "PSW",
        "PSP",
        "PSN",
        "PSL",
        "PSI",
        "PSH",
        "PSG",
        "PSE",
        "PSD",
        "PSC",
        "PSB",
        "PRT",
        "PRO",
        "PRE",
        "PRC",
        "PQN",
        "PPY",
        "PPT",
        "PPS",
        "PPP",
        "PPI",
        "PPH",
        "PPE",
        "PPC",
        "POW",
        "POV",
        "POT",
        "POS",
        "POM",
        "POB",
        "PNT",
        "PNP",
        "PNJ",
        "PNG",
        "PND",
        "PNC",
        "PMW",
        "PMT",
        "PMS",
        "PMP",
        "PMJ",
        "PMG",
        "PMC",
        "PMB",
        "PLX",
        "PLP",
        "PLO",
        "PLE",
        "PLC",
        "PLA",
        "PJT",
        "PJS",
        "PJC",
        "PIV",
        "PIT",
        "PIS",
        "PID",
        "PIC",
        "PIA",
        "PHS",
        "PHR",
        "PHP",
        "PHN",
        "PHH",
        "PHC",
        "PGV",
        "PGT",
        "PGS",
        "PGN",
        "PGI",
        "PGD",
        "PGC",
        "PGB",
        "PFL",
        "PET",
        "PEQ",
        "PEN",
        "PEG",
        "PEC",
        "PDV",
        "PDT",
        "PDR",
        "PDN",
        "PDC",
        "PDB",
        "PCT",
        "PCN",
        "PCM",
        "PCH",
        "PCG",
        "PCF",
        "PCE",
        "PCC",
        "PC1",
        "PBT",
        "PBP",
        "PBC",
        "PAT",
        "PAS",
        "PAP",
        "PAN",
        "PAI",
        "PAC",
        "ORS",
        "OPC",
        "ONW",
        "ONE",
        "OIL",
        "OGC",
        "ODE",
        "OCH",
        "OCB",
        "NXT",
        "NWT",
        "NVT",
        "NVP",
        "NVL",
        "NVB",
        "NUE",
        "NTW",
        "NTT",
        "NTP",
        "NTL",
        "NTH",
        "NTF",
        "NTC",
        "NTB",
        "NT2",
        "NST",
        "NSS",
        "NSL",
        "NSH",
        "NSG",
        "NSC",
        "NS3",
        "NS2",
        "NRC",
        "NQT",
        "NQN",
        "NQB",
        "NOS",
        "NO1",
        "NNT",
        "NNQ",
        "NNG",
        "NNC",
        "NLS",
        "NLG",
        "NKG",
        "NJC",
        "NHV",
        "NHT",
        "NHP",
        "NHH",
        "NHC",
        "NHA",
        "NGC",
        "NFC",
        "NET",
        "NEM",
        "NED",
        "NDX",
        "NDW",
        "NDT",
        "NDP",
        "NDN",
        "NDF",
        "NDC",
        "ND2",
        "NCT",
        "NCS",
        "NCG",
        "NBW",
        "NBT",
        "NBP",
        "NBE",
        "NBC",
        "NBB",
        "NAW",
        "NAV",
        "NAU",
        "NAS",
        "NAP",
        "NAG",
        "NAF",
        "NAC",
        "NAB",
        "MZG",
        "MXC",
        "MWG",
        "MVN",
        "MVC",
        "MVB",
        "MTX",
        "MTV",
        "MTS",
        "MTP",
        "MTL",
        "MTH",
        "MTG",
        "MTC",
        "MTB",
        "MTA",
        "MST",
        "MSR",
        "MSN",
        "MSH",
        "MSB",
        "MRF",
        "MQN",
        "MQB",
        "MPY",
        "MPT",
        "MPC",
        "MND",
        "MNB",
        "MML",
        "MLS",
        "MLC",
        "MKV",
        "MKP",
        "MIM",
        "MIG",
        "MIE",
        "MIC",
        "MHL",
        "MHC",
        "MH3",
        "MGR",
        "MGG",
        "MGC",
        "MFS",
        "MES",
        "MEL",
        "MEG",
        "MEF",
        "MED",
        "MEC",
        "MDG",
        "MDF",
        "MDC",
        "MDA",
        "MCP",
        "MCO",
        "MCM",
        "MCI",
        "MCH",
        "MCG",
        "MCF",
        "MCD",
        "MCC",
        "MC3",
        "MBT",
        "MBS",
        "MBN",
        "MBG",
        "MBB",
        "MAS",
        "MAC",
        "MA1",
        "M10",
        "LYF",
        "LWS",
        "LUT",
        "LTG",
        "LTC",
        "LSS",
        "LSG",
        "LQN",
        "LPT",
        "LPB",
        "LO5",
        "LNC",
        "LMI",
        "LMH",
        "LMC",
        "LM8",
        "LM7",
        "LM3",
        "LLM",
        "LKW",
        "LIX",
        "LIG",
        "LIC",
        "LHG",
        "LHC",
        "LGM",
        "LGL",
        "LGC",
        "LG9",
        "LEC",
        "LDW",
        "LDP",
        "LDG",
        "LCW",
        "LCS",
        "LCM",
        "LCG",
        "LCD",
        "LCC",
        "LBM",
        "LBE",
        "LBC",
        "LAW",
        "LAS",
        "LAI",
        "LAF",
        "L63",
        "L62",
        "L61",
        "L45",
        "L44",
        "L43",
        "L40",
        "L35",
        "L18",
        "L14",
        "L12",
        "L10",
        "KWA",
        "KVC",
        "KTW",
        "KTT",
        "KTS",
        "KTL",
        "KTC",
        "KSV",
        "KST",
        "KSS",
        "KSQ",
        "KSH",
        "KSF",
        "KSD",
        "KSB",
        "KPF",
        "KOS",
        "KMT",
        "KMR",
        "KLM",
        "KLF",
        "KLB",
        "KKC",
        "KIP",
        "KHW",
        "KHS",
        "KHP",
        "KHL",
        "KHG",
        "KHD",
        "KHB",
        "KHA",
        "KGM",
        "KDM",
        "KDH",
        "KDC",
        "KCE",
        "KCB",
        "KBC",
        "KAC",
        "JVC",
        "JOS",
        "IVS",
        "ITS",
        "ITQ",
        "ITD",
        "ITC",
        "ITA",
        "IST",
        "ISH",
        "ISG",
        "IRC",
        "IPH",
        "IPA",
        "INN",
        "ING",
        "INC",
        "IN4",
        "IMP",
        "IME",
        "ILS",
        "ILC",
        "ILB",
        "ILA",
        "IJC",
        "IHK",
        "IFS",
        "IDV",
        "IDP",
        "IDJ",
        "IDI",
        "IDC",
        "ICT",
        "ICN",
        "ICI",
        "ICG",
        "ICF",
        "ICC",
        "IBN",
        "IBD",
        "IBC",
        "HWS",
        "HVX",
        "HVT",
        "HVN",
        "HVH",
        "HVG",
        "HVA",
        "HUX",
        "HUT",
        "HUG",
        "HUB",
        "HU6",
        "HU4",
        "HU3",
        "HU1",
        "HTW",
        "HTV",
        "HTT",
        "HTR",
        "HTP",
        "HTN",
        "HTM",
        "HTL",
        "HTK",
        "HTI",
        "HTH",
        "HTG",
        "HTE",
        "HTC",
        "HT1",
        "HSV",
        "HSP",
        "HSM",
        "HSL",
        "HSI",
        "HSG",
        "HSA",
        "HRT",
        "HRC",
        "HRB",
        "HQC",
        "HPX",
        "HPW",
        "HPT",
        "HPP",
        "HPO",
        "HPM",
        "HPI",
        "HPH",
        "HPG",
        "HPD",
        "HPB",
        "HOT",
        "HOM",
        "HNT",
        "HNR",
        "HNP",
        "HNM",
        "HNI",
        "HNG",
        "HNF",
        "HNE",
        "HND",
        "HNB",
        "HNA",
        "HMS",
        "HMR",
        "HMH",
        "HMG",
        "HMD",
        "HMC",
        "HLY",
        "HLT",
        "HLS",
        "HLR",
        "HLO",
        "HLG",
        "HLE",
        "HLD",
        "HLC",
        "HLB",
        "HLA",
        "HKT",
        "HKP",
        "HKB",
        "HJS",
        "HJC",
        "HIO",
        "HII",
        "HIG",
        "HID",
        "HHV",
        "HHS",
        "HHR",
        "HHP",
        "HHN",
        "HHG",
        "HHC",
        "HHB",
        "HGW",
        "HGT",
        "HGR",
        "HGM",
        "HGC",
        "HGA",
        "HFX",
        "HFC",
        "HFB",
        "HEV",
        "HES",
        "HEP",
        "HEM",
        "HEJ",
        "HEC",
        "HDW",
        "HDS",
        "HDP",
        "HDO",
        "HDM",
        "HDG",
        "HDC",
        "HDB",
        "HDA",
        "HD8",
        "HD6",
        "HD2",
        "HCT",
        "HCM",
        "HCI",
        "HCD",
        "HCC",
        "HCB",
        "HC3",
        "HC1",
        "HBS",
        "HBH",
        "HBD",
        "HBC",
        "HAX",
        "HAW",
        "HAV",
        "HAT",
        "HAS",
        "HAR",
        "HAP",
        "HAN",
        "HAM",
        "HAI",
        "HAH",
        "HAG",
        "HAF",
        "HAD",
        "HAC",
        "HAB",
        "H11",
        "GVT",
        "GVR",
        "GTT",
        "GTS",
        "GTK",
        "GTH",
        "GTD",
        "GTA",
        "GSP",
        "GSM",
        "GQN",
        "GPC",
        "GND",
        "GMX",
        "GMH",
        "GMD",
        "GMC",
        "GMA",
        "GLW",
        "GLT",
        "GLC",
        "GKM",
        "GIL",
        "GIC",
        "GHC",
        "GH3",
        "GGG",
        "GEX",
        "GER",
        "GEG",
        "GEE",
        "GE2",
        "GDW",
        "GDT",
        "GDA",
        "GCF",
        "GCB",
        "GAS",
        "GAB",
        "G36",
        "G20",
        "FTS",
        "FTM",
        "FTI",
        "FT1",
        "FSO",
        "FRT",
        "FRM",
        "FRC",
        "FPT",
        "FOX",
        "FOC",
        "FMC",
        "FLC",
        "FIT",
        "FIR",
        "FID",
        "FIC",
        "FHS",
        "FHN",
        "FGL",
        "FDG",
        "FDC",
        "FCS",
        "FCN",
        "FCM",
        "FCC",
        "FBC",
        "FBA",
        "F88",
        "EVS",
        "EVG",
        "EVF",
        "EVE",
        "EPH",
        "EPC",
        "EMS",
        "EMG",
        "EME",
        "EMC",
        "ELC",
        "EIN",
        "EID",
        "EIC",
        "EIB",
        "EGL",
        "EFI",
        "ECO",
        "ECI",
        "EBS",
        "EAD",
        "E29",
        "E12",
        "DZM",
        "DXV",
        "DXS",
        "DXP",
        "DXL",
        "DXG",
        "DX2",
        "DWS",
        "DWC",
        "DVW",
        "DVT",
        "DVP",
        "DVN",
        "DVM",
        "DVG",
        "DVC",
        "DUS",
        "DTV",
        "DTT",
        "DTP",
        "DTL",
        "DTK",
        "DTI",
        "DTH",
        "DTG",
        "DTE",
        "DTD",
        "DTC",
        "DTB",
        "DTA",
        "DT4",
        "DSV",
        "DST",
        "DSP",
        "DSN",
        "DSH",
        "DSG",
        "DSE",
        "DSD",
        "DSC",
        "DS3",
        "DRL",
        "DRI",
        "DRH",
        "DRG",
        "DRC",
        "DQC",
        "DPS",
        "DPR",
        "DPP",
        "DPM",
        "DPH",
        "DPG",
        "DPD",
        "DPC",
        "DP3",
        "DP2",
        "DP1",
        "DOP",
        "DOC",
        "DNW",
        "DNT",
        "DNP",
        "DNN",
        "DNM",
        "DNL",
        "DNH",
        "DNE",
        "DND",
        "DNC",
        "DNB",
        "DNA",
        "DMS",
        "DMN",
        "DMC",
        "DM7",
        "DLT",
        "DLR",
        "DLM",
        "DLG",
        "DLD",
        "DL1",
        "DKW",
        "DKH",
        "DKG",
        "DKC",
        "DIH",
        "DIG",
        "DID",
        "DIC",
        "DHT",
        "DHP",
        "DHN",
        "DHM",
        "DHG",
        "DHD",
        "DHC",
        "DHB",
        "DHA",
        "DGW",
        "DGT",
        "DGC",
        "DFF",
        "DFC",
        "DDV",
        "DDN",
        "DDM",
        "DDH",
        "DDG",
        "DDB",
        "DCT",
        "DCS",
        "DCR",
        "DCM",
        "DCL",
        "DCH",
        "DCG",
        "DCF",
        "DC4",
        "DC2",
        "DC1",
        "DBW",
        "DBT",
        "DBM",
        "DBH",
        "DBD",
        "DBC",
        "DAT",
        "DAS",
        "DAR",
        "DAN",
        "DAH",
        "DAG",
        "DAE",
        "DAD",
        "DAC",
        "D2D",
        "D17",
        "D11",
        "CYC",
        "CX8",
        "CVT",
        "CVP",
        "CVN",
        "CTX",
        "CTW",
        "CTT",
        "CTS",
        "CTR",
        "CTP",
        "CTN",
        "CTI",
        "CTG",
        "CTF",
        "CTD",
        "CTC",
        "CTB",
        "CTA",
        "CT6",
        "CT5",
        "CT3",
        "CSV",
        "CST",
        "CSM",
        "CSI",
        "CSC",
        "CRV",
        "CRE",
        "CRC",
        "CQT",
        "CQN",
        "CPI",
        "CPH",
        "CPC",
        "CPA",
        "COM",
        "CNT",
        "CNN",
        "CNG",
        "CNC",
        "CNA",
        "CMX",
        "CMW",
        "CMV",
        "CMT",
        "CMS",
        "CMP",
        "CMN",
        "CMM",
        "CMK",
        "CMI",
        "CMG",
        "CMF",
        "CMD",
        "CMC",
        "CLX",
        "CLW",
        "CLM",
        "CLL",
        "CLH",
        "CLG",
        "CLC",
        "CKV",
        "CKG",
        "CKD",
        "CKA",
        "CK8",
        "CJC",
        "CIP",
        "CII",
        "CIG",
        "CID",
        "CIA",
        "CI5",
        "CHS",
        "CHP",
        "CHC",
        "CH5",
        "CGV",
        "CGL",
        "CFV",
        "CFM",
        "CET",
        "CEO",
        "CEN",
        "CEG",
        "CEE",
        "CE1",
        "CDR",
        "CDP",
        "CDO",
        "CDN",
        "CDH",
        "CDG",
        "CDC",
        "CCV",
        "CCT",
        "CCR",
        "CCP",
        "CCM",
        "CCL",
        "CCI",
        "CCC",
        "CCA",
        "CC4",
        "CC1",
        "CBS",
        "CBI",
        "CAV",
        "CAT",
        "CAR",
        "CAP",
        "CAN",
        "CAG",
        "CAD",
        "CAB",
        "C92",
        "C69",
        "C4G",
        "C47",
        "C32",
        "C22",
        "C21",
        "C12",
        "BXT",
        "BXH",
        "BWS",
        "BWE",
        "BWA",
        "BVS",
        "BVN",
        "BVL",
        "BVH",
        "BVG",
        "BVB",
        "BUD",
        "BTW",
        "BTV",
        "BTU",
        "BTT",
        "BTS",
        "BTP",
        "BTN",
        "BTH",
        "BTG",
        "BTD",
        "BTB",
        "BT6",
        "BT1",
        "BST",
        "BSR",
        "BSQ",
        "BSP",
        "BSL",
        "BSI",
        "BSH",
        "BSG",
        "BSD",
        "BSC",
        "BSA",
        "BRS",
        "BRR",
        "BRC",
        "BQP",
        "BQB",
        "BPW",
        "BPC",
        "BOT",
        "BNW",
        "BNA",
        "BMV",
        "BMS",
        "BMP",
        "BMN",
        "BMK",
        "BMJ",
        "BMI",
        "BMG",
        "BMF",
        "BMD",
        "BMC",
        "BLW",
        "BLU",
        "BLT",
        "BLN",
        "BLI",
        "BLF",
        "BKH",
        "BKG",
        "BKC",
        "BIO",
        "BII",
        "BIG",
        "BID",
        "BIC",
        "BHT",
        "BHP",
        "BHN",
        "BHK",
        "BHI",
        "BHH",
        "BHG",
        "BHC",
        "BHA",
        "BGW",
        "BGE",
        "BFC",
        "BEL",
        "BED",
        "BDW",
        "BDT",
        "BDG",
        "BDB",
        "BCV",
        "BCR",
        "BCP",
        "BCO",
        "BCM",
        "BCG",
        "BCF",
        "BCE",
        "BCC",
        "BCB",
        "BCA",
        "BBT",
        "BBS",
        "BBM",
        "BBH",
        "BBC",
        "BAX",
        "BAL",
        "BAF",
        "BAB",
        "B82",
        "AVG",
        "AVF",
        "AVC",
        "AUM",
        "ATS",
        "ATG",
        "ATB",
        "ATA",
        "AST",
        "ASP",
        "ASM",
        "ASG",
        "ASA",
        "ART",
        "ARM",
        "APT",
        "APS",
        "APP",
        "APL",
        "API",
        "APH",
        "APG",
        "APF",
        "APC",
        "ANV",
        "ANT",
        "AMV",
        "AMS",
        "AMP",
        "AME",
        "AMD",
        "AMC",
        "ALV",
        "ALT",
        "AIG",
        "AIC",
        "AGX",
        "AGR",
        "AGP",
        "AGM",
        "AGG",
        "AGF",
        "AGE",
        "AG1",
        "AFX",
        "ADS",
        "ADP",
        "ADG",
        "ADC",
        "ACV",
        "ACS",
        "ACM",
        "ACL",
        "ACG",
        "ACE",
        "ACC",
        "ACB",
        "ABW",
        "ABT",
        "ABS",
        "ABR",
        "ABI",
        "ABC",
        "ABB",
        "AAV",
        "AAT",
        "AAS",
        "AAM",
        "AAH",
        "AAA",
        "A32",
    ]
    print(f"-> Đang quét {len(test_tickers)} mã")

    start_time = time.time()
    all_news_collection = []

    with concurrent.futures.ThreadPoolExecutor(max_workers=max_workers) as executor:
        future_to_symbol = {
            executor.submit(_fetch_symbol_news, symbol, target_date, SLEEP_TIME): symbol
            for symbol in test_tickers
        }

        for idx, future in enumerate(concurrent.futures.as_completed(future_to_symbol), start=1):
            symbol = future_to_symbol[future]
            try:
                news_list = future.result()
                all_news_collection.extend(news_list)
            except Exception as exc:  # pragma: no cover - chỉ log
                print(f"  -> Lỗi khi lấy {symbol}: {exc}")

            if idx % 100 == 0:
                progress = idx / len(test_tickers) * 100
                print(f"  -> Đã xử lý {idx}/{len(test_tickers)} mã ({progress:.1f}%)")

    unique_news = _deduplicate_news(all_news_collection)

    duration = time.time() - start_time
    print("\n=== HOÀN TẤT ===")
    print(f"Thời gian chạy: {duration:.2f} giây | Bài báo duy nhất: {len(unique_news)}")
    return unique_news


def fetch_news_df(target_date: str | None = None, max_workers: int | None = None) -> pd.DataFrame:
    """Lấy tin theo ngày và trả về DataFrame đã chuẩn hóa để ghi CSV."""
    records = fetch_news_test(target_date=target_date, max_workers=max_workers) or []
    if not records:
        return pd.DataFrame()

    df = pd.DataFrame(records)
    if df.empty:
        return df

    required_cols = [
        "author",
        "friendly_sub_title",
        "news_source_link",
        "created_at",
        "public_date",
        "updated_at",
        "lang_code",
        "news_short_content",
        "news_full_content",
        "price_change_pct",
        "fetched_at",
        "related_ticker",
        "news_id",
        "id",
    ]
    for col in required_cols:
        if col not in df.columns:
            df[col] = None

    if df["news_id"].isna().all():
        df["news_id"] = df["id"]
    else:
        df["news_id"] = df["news_id"].fillna(df["id"])

    df.dropna(subset=["news_id", "related_ticker"], inplace=True)
    if df.empty:
        return pd.DataFrame()

    df["news_id"] = df["news_id"].astype(str).str.strip()
    df["related_ticker"] = df["related_ticker"].astype(str).str.upper().str.strip()
    df = df[df["related_ticker"] != ""]

    datetime_cols = ["created_at", "updated_at", "fetched_at"]
    for col in datetime_cols:
        df[col] = pd.to_datetime(df[col], errors="coerce", utc=True)
    df["public_date"] = pd.to_datetime(df["public_date"], errors="coerce").dt.date
    df["price_change_pct"] = pd.to_numeric(df["price_change_pct"], errors="coerce")

    df.drop_duplicates(subset=["news_id", "related_ticker"], keep="last", inplace=True)
    if df.empty:
        return pd.DataFrame()

    target_dt = pd.to_datetime(target_date or datetime.now().date()).date()
    df["ds"] = target_dt

    return df[
        [
            "news_id",
            "related_ticker",
            "author",
            "friendly_sub_title",
            "news_source_link",
            "created_at",
            "public_date",
            "updated_at",
            "lang_code",
            "news_short_content",
            "news_full_content",
            "price_change_pct",
            "fetched_at",
            "ds",
        ]
    ]


if __name__ == "__main__":
    fetch_news_test()
